### ISSUE TITLE
微调embedding

### ISSUE THREAD

**Issue by zzzcccxx** [LikeGiver/news_bot#2]
感谢分享，请问只是用chatglm3作为推理了吗，如果我想用llama_index来对embedding进行微调的话，我可以怎么做呢？看了llama_index的文档没有写如何用自己的LLM进行数据集的生成，文档中只写了使用openai_key。

**Comment by LikeGiver** [comment]
是的，本项目还没有进行微调，用chatglm3就是纯推理，而且现在RAG效果还不是很好（和该项目进行比较，[FastGPT](https://github.com/labring/FastGPT)的RAG效果似乎好上不少），embedding的fintune应该可以参考[llamaindex官方文档finetune部分](https://docs.llamaindex.ai/en/latest/examples/finetuning/embeddings/finetune_embedding.html#)
